name: 'Miodrag Spasojevic'
description: 'Used to annotate based on a json input'
author: 'AMD'
inputs:
  result_json:
    required: true
    description: 'json string input for annotations'
    default: '{}'
  owner:
    required: true
    description: 'owner'
    default: ''
  repo:
    required: true
    description: 'repo'
    default: ''
  name:
    required: true
    description: 'Reasonable name'
    default: ''
  title:
    required: true
    description: 'Reasonable title'
    default: ''
  pat:
    required: true
    description: 'PAT used for authorization'
    default: ''
  head_sha:
    required: true
    description: 'SHA of the commit to create check for'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
