name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          result_json: '{"ValidMatches":{"Blocker":0,"Warning":1,"ShouldBeFixed":2,"Informational":3},"ScanStartTime":"01-01-23","ScanEndTime":"01-01-23","SourceId":"${{github.sha}}","Annotations":[{"Path":".github/workflows/test.yml","Level":"warning","StartLine":26,"EndLine":26,"Message":"Some stuff"},{"Path":".github/workflows/test.yml","Level":"failure","StartLine":21,"EndLine":21,"Message":"Some stuff"}]}'
          owner: 'mspasoje'
          repo: 'kws-annotate'
          name: 'Some nice name'
          title: 'Legendary title'
          pat: ${{ secrets.GITHUB_TOKEN }}
          head_sha: ${{ github.sha }}
