name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          result_json: '{}'
          owner: 'mspasoje'
          repo: 'kws-annotate'
          name: 'Some nice name'
          title: 'Legendary title'
          pat: ${{ secrets.GITHUB_TOKEN }}
          head_sha: ${GITHUB_SHA}

